name: Auto Approve

on:
  workflow_run:
    workflows: ["check-flake"]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.actor.login == github.repository_owner || github.event.workflow_run.actor.login == 'github-actions[bot]') &&
      contains(github.event.workflow_run.pull_requests[0].labels.*.name, 'automated')
    steps:
      - name: Approve PR
        env:
          PR_URL: ${{ github.event.workflow_run.pull_requests[0].url }}
        run: gh pr review --approve "$PR_URL"
      - name: Enable Auto-Merge
        env:
          PR_URL: ${{ github.event.workflow_run.pull_requests[0].url }}
        run: gh pr merge --auto --squash "$PR_URL"