name: "Flake.nix: check Nix flake"

on:
  push:
    branches:
      - main
      - 'deps/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  nix-flake-check:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout source branch (head)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check --all-systems --show-trace
