# To use this workflow, create and use PAT.
# https://github.com/DeterminateSystems/update-flake-lock/tree/main#running-github-actions-ci

name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Generate branch date
        run: |
          echo "CURRENT_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          nix-options: --debug --log-format raw
          branch: "deps/update-flake-lock-${{ env.CURRENT_DATE }}"
          commit-msg: "ci: Update flake.lock"
          pr-title: "Update Nix flake inputs" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
          # To trigger another workflows automatically
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}

